<?php
/**
 * Created by PhpStorm.
 * User: adsitalo
 * Date: 18.12.2017
 * Time: 14:31
 */

namespace app\components;
use app\models\Brand;
use app\models\Product;
use yii\base\Widget;
use app\models\Category;
use Yii;

class BrandWidget extends Widget
{
    public $data;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->tpl===null){
            $this->tpl='menu';
        }
        $this->tpl.='.php';
    }

    public function run(){
        $this->data=Brand::find();
        $this->tree=$this->getCountProduct();
        $this->menuHtml=$this->getMenuHtml($this->tree);
        Yii::$app->cache->set('menu',$this->menuHtml,60*60);
        return $this->menuHtml;
    }

}