<?php
/**
 * Created by PhpStorm.
 * User: adsitalo
 * Date: 18.12.2017
 * Time: 14:31
 */

namespace app\components;
use app\models\Brand;
use app\models\Product;
use yii\base\Widget;
use app\models\Category;
use Yii;

class BrandWidget extends Widget
{
    public $data;
    public $tpl;
    public $menuHtml;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->tpl===null){
            $this->tpl='menu';
        }
        $this->tpl.='.php';
    }

    public function run(){
        $this->data=Brand::find()->all();
        $this->menuHtml=$this->getMenuHtml($this->data);
        return $this->menuHtml;
    }
    protected function getMenuHtml($data){
        $str='';

        foreach($data as $brand){
            $countBrad=Product::find()->where(['idBrand'=>$brand->id])->count();
            $str .=$this->catToTamplate($brand,$countBrad);
        }
        return $str;
    }

    protected function catToTamplate($brand,$countBrad){
        ob_start();
        include __DIR__ . '/brand_tpl/' .$this->tpl;
        return ob_get_clean();
    }

}