<?php
/**
 * Created by PhpStorm.
 * User: Andrey
 * Date: 01.12.2017
 * Time: 17:10
 */
namespace app\models;
use yii\db\ActiveRecord;

class Category extends ActiveRecord{

    public static function tableName(){
        return 'categories'; // TODO: Change the autogenerated stub
    }

    public function getProduct(){
        return $this->hasMany(Product::className(),['idCategory'=>'id']);

    }
}