<?php
/**
 * Created by PhpStorm.
 * User: Andrey
 * Date: 01.12.2017
 * Time: 17:10
 */
namespace app\models;
use yii\db\ActiveRecord;

class Product extends ActiveRecord{

    public static function tableName(){
        return 'product'; // TODO: Change the autogenerated stub
    }

    public function getCategiry(){
        return $this->hasOne(Category::className(),['id'=>'idCategory']);

    }
}